name: route_dashboard                                                                                                                                                                          
channels:                                                                                                                                                                                        
  - snowflake   
dependencies:
  - streamlit
  - pandas                                                                                                                                                                                       
  - plotly
  - pydeck  